Git clone error
Git clone refuses to clone this file. Possible because of the file name that is illegal under Windows.
```bash
error: invalid path 'src/Gastromio.App/ClientApp/src/assets/fonts/apercu/apercu-black-italic-pro.eot?#iefix'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```